import Head from "next/head";
import Navbar from "@/components/nav";
import { MdSortByAlpha } from "react-icons/md";
import { ReactElement, useState } from "react";
import React from "react";
export default function Layout({
  children,
  tsetstate,
  tstate // will be a page or nested layout
}: {
  children: React.ReactElement;
  tstate: string;
  tsetstate: (c: string)=>void;
}) {
  return (
    <>
      <Head>
        <title>Invntry</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-row min-h-screen max-h-screen overflow-hidden">
        <Navbar />
        <div className="bg-white dark:text-white dark:bg-sexyblack grow flex flex-col flex-1">
          <div className="max-w-full bg-sexygray h-16 max-h-16">
            <div className="p-4 flex flex-row justify-between text-center">
              <div>
                <input
                  type="search"
                  className="form-control flex-auto min-w-0 px-3 py-1.5 text-base font-normal text-white bg-sexyblack border border-none rounded focus:outline-none"
                  placeholder="Search"
                  value={tstate}
                  onChange={e => { tsetstate(e.currentTarget.value); }}
                  aria-label="Search"
                  aria-describedby="button-addon2"
                ></input>
              </div>
              <button className="bg-zinc-800 rounded-full px-4 py-1">
                <MdSortByAlpha className="h-6 w-6 text-white" />
              </button>
            </div>
          </div>
          {children}
        </div>
      </main>
    </>
  );
}
